config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  # resources :users, only: [:show]
  get "/dashboard", to: "pages#dashboard"
  get "/wall", to: "pages#wall"
  get "/search", to: "pages#search"
  get "/search_bookmarks", to: "pages#search_bookmarks"
  get "/bookmarks", to: "pages#bookmarks"
  get "/home", to: "pages#home_first"
  get "/profiles/:id", to: "pages#pub_profile", as: "profiles"
  get "/avatar_creation", to: "pages#avatar_creation", as: "avatar"

  post '/pages/ajax', to: 'pages#create_ajax'


  patch "/profiles/:id", to: "pages#toggle_fav"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :favorites
  post '/favorites/:id/create_fav_th', to: 'favorites#create_fav_th', as: 'create_fav_th'
  post '/favorites/:id/create_fav_art', to: 'favorites#create_fav_art', as: 'create_fav_art'
  post '/favorites/:id/create_fav_user', to: 'favorites#create_fav_user', as: 'create_fav_user'
  post '/articles_selectedth', to: 'articles#create_art_selectedth', as: 'create_art_selectedth'
  resources :articles
  resources :articles do
    resources :comments, only: [ :new, :create, :index, :destroy ]
    resources :votes, only: [ :new, :create, :destroy ]
  end
  resources :themes
  resources :themes, only: [:show] do
    get '/articles', to: 'articles#index'
  end
  get '/favorites_th', to: 'favorites#index_th'
  get '/favorites_art', to: 'favorites#index_art'
  get '/favorites_user', to: 'favorites#index_user'
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  searchkick language: "french"
  belongs_to :user
  belongs_to :favoritable, polymorphic: true
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  after_action :verify_policy_scoped, only: [ :index, :index_th, :index_art, :index_user ], unless: :skip_pundit?
  after_action :verify_authorized, except: [ :index, :index_th, :index_art, :index_user ], unless: :skip_pundit?

  def index
    @favorites = policy_scope(Favorite)
    @favorites_group = @favorites.select(:favoritable_type).group(:favoritable_type).count
  end

  def index_th
    # @favorites = FavoritePolicy::Scope.new(current_user, Favorite).resolve
    @favorites = policy_scope(Favorite)
    # @favorites = Favorite.all
  end

  def index_art
    # @favorites = FavoritePolicy::Scope.new(current_user, Favorite).resolve

    @scope = "favoris"
    # @favorites = policy_scope(Favorite)  current_user.favorites
    @array_ranked_articles = policy_scope(Favorite).where(user_id: current_user.id, favoritable_type: "Article")
    @articles = Array.new
    @array_ranked_articles.each do |item|
      @articles << item.favoritable
    end
    # @favorites = Favorite.all
  end

  def index_user
    # @favorites = FavoritePolicy::Scope.new(current_user, Favorite).resolve
    @favorites = policy_scope(Favorite)
    # @favorites = Favorite.all
  end

  def new
    @favorite = Favorite.new
  end

  def create
    @favorite = Favorite.new(favorite_params)
    redirect_to themes_path
  end


  def create_fav_th
    @favorite = Favorite.new
    if current_user.favorites.where(favoritable_type: "Theme").where(favoritable_id: params[:id]).count == 0
      @theme = Theme.find(params[:id])
      authorize @favorite
      @favorite.user = current_user
      @favorite.favoritable = @theme
      @favorite.save
    end
    authorize @favorite
    redirect_to favorites_th_path
  end


  def create_fav_art
    @article = Article.find(params[:id])
    @favorite = current_user.favorites.where(favoritable_type: "Article").find_by(favoritable_id: params[:id])
    if @favorite
      authorize @favorite
      @favorite.destroy
    else
      @article = Article.find(params[:id])
      @favorite = Favorite.new
      authorize @favorite
      @favorite.user = current_user
      @favorite.favoritable = @article
      @favorite.save
    end
    redirect_to article_path(@article)
  end

  def create_fav_user
    @article = Article.find(params[:id])
    @user = @article.user
    @favorite = current_user.favorites.where(favoritable_type: "User").find_by(favoritable_id: @user.id)
      if @favorite
        authorize @favorite
        @favorite.destroy
      else
        @favorite = Favorite.new
        authorize @favorite
        @favorite.user = current_user
        @favorite.favoritable = @user
        @favorite.save
      end
    redirect_to article_path(@article)
  end


  def destroy
    @favorite = Favorite.find(params[:id])
    authorize @favorite
    @favorite.destroy
    redirect_to favorites_th_path
  end



private

  def favorite_params
    params.require(:favorite).permit(:user_id, :favoritable)
  end


end

app/views/favorites/index.html.erb
<div class="container-general">
  <h3 class="container-title">Tous mes Favoris</h3>

  <% @favorites_group.each do |key, value| %>
    <h4><%= key %> : <%= value %></h4>
    <br>
  <% end %>
</div>

app/views/favorites/index_art.html.erb
<div class="container-general" id="index-art-page">
  <div class="spacer">
  </div>
  <div class="mt-3">
    <%= render partial: "shared/articles_med_list_col", locals: { articles: @articles, avatar_visible: true, scope: @scope} %>
    <%
=begin%>
 <% @favorites.where(favoritable_type: "Article").each do |favorite| %>
      <div class="card text-white  mb-3 container-general purple text-decoration-none" style="max-width: 18rem;">
        <h5><%= favorite.favoritable.title %></h5>
        <p><%= favorite.favoritable.description %></p>
      </div>

      <%= link_to("+favoris",favorite_path(favorite.id), method: :delete) %>
    <% end %>
<%
=end%>
  </div>
</div>

app/views/favorites/index_th.html.erb
<div class="container-general">
  <h3 class="container-title">Mes Themes Favoris</h3>
  <% @favorites.where(favoritable_type: "Theme").each do |favorite| %>
    <div class="theme border-grey">
      <div class="theme_image">
               <img src="
         <% if (favorite.favoritable.picture.attached?) %>
            <%= cl_image_path(favorite.favoritable.picture.key) %>
          <% else %>
            <%= image_path('frontlorem.jpg') %>
          <% end %>
            "/>
      </div>
      <div class="theme_title">
        <h4><%= favorite.favoritable.title %></h4>
        <p><%= truncate(favorite.favoritable.description, :length => 40) %></p>
        <%# <%= link_to("+Favoris",favorite_path(favorite.id), method: :delete, class:"white-azure") %>
        <%# <%= link_to("Les articles", theme_articles_path(favorite.favoritable), class:"white-azure") %>
      </div>
    </div>
  <% end %>
</div>

app/views/favorites/index_user.html.erb
<div class="container-general">
  <h3 class="container-title">Mes Users Favoris</h3>

  <div class="mt-3">
    <% @favorites.where(favoritable_type: "User").each do |favorite| %>
      <div class="card text-white  mb-3 container-general purple text-decoration-none" style="max-width: 18rem;">
        <h5><%= favorite.favoritable.username %></h5>
        <p><%= favorite.favoritable.biography %></p>
      </div>
      <%= link_to("+favoris",favorite_path(favorite.id), method: :delete) %>
    <% end %>
  </div>
</div>