config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  # resources :users, only: [:show]
  get "/dashboard", to: "pages#dashboard"
  get "/wall", to: "pages#wall"
  get "/search", to: "pages#search"
  get "/search_bookmarks", to: "pages#search_bookmarks"
  get "/bookmarks", to: "pages#bookmarks"
  get "/home", to: "pages#home_first"
  get "/profiles/:id", to: "pages#pub_profile", as: "profiles"
  get "/avatar_creation", to: "pages#avatar_creation", as: "avatar"

  post '/pages/ajax', to: 'pages#create_ajax'


  patch "/profiles/:id", to: "pages#toggle_fav"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :favorites
  post '/favorites/:id/create_fav_th', to: 'favorites#create_fav_th', as: 'create_fav_th'
  post '/favorites/:id/create_fav_art', to: 'favorites#create_fav_art', as: 'create_fav_art'
  post '/favorites/:id/create_fav_user', to: 'favorites#create_fav_user', as: 'create_fav_user'
  post '/articles_selectedth', to: 'articles#create_art_selectedth', as: 'create_art_selectedth'
  resources :articles
  resources :articles do
    resources :comments, only: [ :new, :create, :index, :destroy ]
    resources :votes, only: [ :new, :create, :destroy ]
  end
  resources :themes
  resources :themes, only: [:show] do
    get '/articles', to: 'articles#index'
  end
  get '/favorites_th', to: 'favorites#index_th'
  get '/favorites_art', to: 'favorites#index_art'
  get '/favorites_user', to: 'favorites#index_user'
end

app/models/article.rb
class Article < ApplicationRecord
  searchkick language: "french"
  belongs_to :user
  belongs_to :theme
  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :title, :content, presence: true
  validates :title, length: { minimum: 4 }
  validates :content, length: { minimum: 20 }
  has_one_attached :picture
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @placeholder_value = "ex: post sur 'comment annoncer'..."
    @scope_popular = "les plus populaires"
    @scope_last = "récents"
    @current_path = search_path

    # if params[:theme_id]
    #   @articles = policy_scope(Article).where(theme_id: params[:theme_id])
    #   @theme = Theme.find(params[:theme_id])
    #   authorize @theme
    # else
    #   @articles = policy_scope(Article)
    # end

    @articles_last = policy_scope(Article).all.order(created_at: :desc).limit(50)

    @array_ranked_articles = Favorite.where(favoritable_type: "Article").group("favoritable_id").count.sort_by{|_,v| -v}
    @articles_popular = Array.new
    @array_ranked_articles.each do |item|
      @articles_popular << Article.find(item[0])
    end
  end

  def show
    @article = Article.find(params[:id])
    @comments = @article.comments
    @comment = Comment.new
    authorize @article
  end

  def new
    @article = Article.new
    @themes = Theme.all
    authorize @article
  end

  def create
    @article = Article.new(article_params)
    # @article = Article.new(title: article_params[:title], content: article_params[:content])
    @article.user_id = current_user.id
    authorize @article
    if @article.save
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def create_art_selectedth
    @article = Article.new(article_params)
    # @article = Article.new(title: article_params[:title], content: article_params[:content])
    @article.user_id = current_user.id
    authorize @article
    if @article.save
      redirect_to theme_path(@article.theme)
    else
      render :new
    end
  end

  def edit
    @article = Article.find(params[:id])
    authorize @article
  end

  def update
    @article = Article.find(params[:id])
    @article.update(article_params)
    authorize @article
    redirect_to article_path(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
    authorize @article
  end



  private

  def article_params
    params.require(:article).permit(:title, :theme_id, :content, :picture)
  end

end

app/views/articles/edit.html.erb
<div class="container pt-3">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
      <h1 class="container-title">Modifier un article</h1>
      <%= simple_form_for [ @article ] do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.association :theme %>
        <%= f.input :content %>
        <%= f.submit "Soumettre le post", class: "btn purple white" %>
      <% end %>

      <%= link_to "Supprimer #{@article.title}",
                  article_path(@article),
                  method: :delete,
                  data: { confirm: "Etes vous sur?" } %>

      <%= link_to("Liste des posts", articles_path) %>
    </div>
  </div>
</div>

app/views/articles/index.html.erb
<div class="container-general poppins-font" id="articles-index">
  <div class="spacer">
  </div>
  <%= render partial: "shared/form_searchbar", locals: {placeholder_value: @placeholder_value, currentpath: @currentpath} %>
  <div class="cards-favorites">
      <div class="favorites-th-art">
        <%= render partial: "shared/articles_med_list", locals: { articles: @articles_last, avatar_visible: true, scope: @scope_last } %>
        <%= render partial: "shared/articles_list", locals: { articles: @articles_popular, scope: @scope_popular, add_arrow: false, arrowthemepath: favorites_art_path} %>
      </div>
  </div>
</div>

app/views/articles/new.html.erb
<div class="container pt-3">
  <div class="row justify-content-center">
    <div class="col-12 col-sm-4">
    <h1 class="container-title">Créer un article</h1>
      <%= simple_form_for [ @article ] do |f| %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.association :theme %>
        <%= f.input :content %>
        <%= f.submit "Soumettre le post", class: "btn purple white" %>
      <% end %>

      <%= link_to("Liste des posts", articles_path) %>
    </div>
  </div>
</div>

app/views/articles/show.html.erb
<div class="photo-container" style="background-image: url('<%= @article.picture.attached? ? cl_image_path(@article.picture.key) : 'https://images.unsplash.com/photo-1543932927-a9def13a0e7c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8Y291cGxlfGVufDB8fDB8fA%3D%3D&auto=format&fit=crop&w=500&q=60' %>'">
</div>

<div class="container-smaller" id="articles-show">
  <div class="header-content">
    <h2 class="title-main"><%= @article.title %></h2>
    <div class="container-icons">
      <div class="image-avatar">
        <a href=<%= profiles_path(@article.user) %>>
        <% if @article.user.picture.attached? %>
          <%=  cl_image_tag @article.user.picture.key, height: 50, width: 50, class: "user-img-circle" %>
          <% else %>
          <%= image_tag('avatar.png', class: "avatar-mini") %>
        <% end %>
        </a>
        <div class="plus-icon">
          <%= link_to create_fav_user_path(@article.id), method: :post do %>
            <% if current_user.favorites.find_by(favoritable: @article.user)%>
             <i class="fas fa-minus-circle"></i>
            <% else %>
              <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#902CB8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-circle"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="8" x2="12" y2="16"></line><line x1="8" y1="12" x2="16" y2="12"></line></svg>
            <% end %>
          <% end %>
        </div>
      </div>
      <div class="username-title">
        <%= @article.user.username %>
      </div>
      <div class="sub-container-icons">
        <%= link_to(article_votes_path(@article, reaction: 1), method: :post)  do %>
          <% if (@current_user.votes.find_by(article: @article))%>
            <i class="fas fa-heart"></i>
          <% else %>
            <i class="far fa-heart"></i>
          <% end %>
        <% end %>

        <%= link_to(create_fav_art_path(@article.id), method: :post) do %>
          <% if @current_user.favorites.find_by(favoritable: @article)%>
            <i class="fas fa-bookmark"></i>
          <% else %>
            <i class="far fa-bookmark"></i>
          <% end %>
        <% end %>

      </div>
    </div>
  </div>

  <h2 class="title-h2"><%= @article.description %></h2>
  <p class="article-content"><%= @article.content %></p>

  <% if policy(@article).destroy? %>
    <%= link_to("delete", article_path(@article), method: :delete, data: { confirm: "Are you sure?" }) %>
  <% end %>
  <ul class="list-group">
    <div>
      <% @comments.each do |comment| %>
        <div class="border-comment">
          <div class="text-comment" id="<%= comment.id%>">
            <%= comment.content %>
          </div>
          <div>
            <ul><%= comment.created_at.to_datetime.strftime("Publié le %m/%d/%Y") %> par <%= comment.user.username %>
              <% if policy(comment).destroy? %>
                <%= link_to("supprimer", article_comment_path(@article, comment), method: :delete, data: { confirm: "Are you sure?" }) %>
              <% end %>
            </ul>
          </div>
        </div>
      <% end %>
    </div>
  </ul>



  <%= simple_form_for [ @article, @comment ] do |f| %>
    <%= f.input :content, :label => 'Votre commentaire' %>
    <%= f.submit "Commenter", class: "btn purple white" %>
  <% end %>

</div>