config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users
  root to: 'pages#home'

  # resources :users, only: [:show]
  get "/dashboard", to: "pages#dashboard"
  get "/wall", to: "pages#wall"
  get "/search", to: "pages#search"
  get "/search_bookmarks", to: "pages#search_bookmarks"
  get "/bookmarks", to: "pages#bookmarks"
  get "/home", to: "pages#home_first"
  get "/profiles/:id", to: "pages#pub_profile", as: "profiles"
  get "/avatar_creation", to: "pages#avatar_creation", as: "avatar"

  post '/pages/ajax', to: 'pages#create_ajax'


  patch "/profiles/:id", to: "pages#toggle_fav"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :favorites
  post '/favorites/:id/create_fav_th', to: 'favorites#create_fav_th', as: 'create_fav_th'
  post '/favorites/:id/create_fav_art', to: 'favorites#create_fav_art', as: 'create_fav_art'
  post '/favorites/:id/create_fav_user', to: 'favorites#create_fav_user', as: 'create_fav_user'
  post '/articles_selectedth', to: 'articles#create_art_selectedth', as: 'create_art_selectedth'
  resources :articles
  resources :articles do
    resources :comments, only: [ :new, :create, :index, :destroy ]
    resources :votes, only: [ :new, :create, :destroy ]
  end
  resources :themes
  resources :themes, only: [:show] do
    get '/articles', to: 'articles#index'
  end
  get '/favorites_th', to: 'favorites#index_th'
  get '/favorites_art', to: 'favorites#index_art'
  get '/favorites_user', to: 'favorites#index_user'
end

app/views/shared/_articles_list.erb
 <div class="articles-list">
  <div class="favorites-title">
    <div class="favorites-title-col">
      <%= image_tag('article-purple.svg') %>
      <span>Articles <%= scope %></span>
    </div>
    <% if add_arrow %>
      <%= link_to image_tag('arrow-double-fat.svg'), arrowthemepath %>
    <% end %>
  </div>
  <% articles.each do |article| %>
  <div class="mini-articles-card">
    <a href=<%= article_path(article) %>>
          <div class="art-description">
            <div class="art-description-col1">
              <span class="art-title"><%= article.title %></span>
              <div class="art-th-description">
                <span class="art-theme"><%= article.theme.title %></span>
                <%= image_tag('ellipse.svg', class: 'ellipse-th') %>
                <span class="art-created">
                  <% if TimeDifference.between(article.updated_at, Time.now).in_days.round >0 %>
                      Il y a <%= TimeDifference.between(article.updated_at, Time.now).in_days.round %> jours
                  <% else %>
                      aujourd'hui
                  <% end %>
                </span>
              </div>
            </div>
              <% if (article.picture.attached?) %>
                <%= cl_image_tag(article.picture.key, class: 'mini-article-img') %>
              <% else %>
                <%= image_tag('avatar.png', class: 'mini-article-img') %>
              <% end %>
          </div>
    </a>
  </div>
  <% end %>
</div>
<div class="no-favorites">
  <%= @no_favorites %>
</div>

app/views/shared/_articles_med_list.erb
<div class="favorites-title">
  <div class="favorites-title-col">
    <%= image_tag('article-new.svg') %>
    <span>Articles <%= scope %></span>
  </div>
</div>
<div class="article-cards">
  <% articles.each do |article| %>
  <div class="article-card">
    <div class="article-card-image"  style="background: url(
          <% if (article.picture.attached?) %>
              <%= cl_image_path(article.picture.key) %>
            <% else %>
              <%= image_path('frontlorem.jpg') %>
            <% end %>
              ), #F4EAF8; background-repeat: no-repeat; background-size: 100%; background-position: 50% 50%;">
    </div>
    <div class="article-card-title art-title">
      <%= article.title %>
    </div>
    <div class="article-card-details">
      <% if avatar_visible == true %>
      <div class="article-card-details-avatar">
        <div class="">
          <%= link_to profiles_path(article.user.id) do %>
            <% if (article.user.picture.attached?) %>
            <%= cl_image_tag(article.user.picture.key, class: 'avatar-small') %>
              <% else %>
            <%= image_tag('avatar.png', class: 'avatar-small') %>
            <% end %>
          <% end %>
        </div>
        <div class="article-card-details-name">
          <span class="mini-user-name"><%= article.user.username %></span>
        </div>
      </div>
      <% end %>
      <div class="article-card-details-theme art-theme">
        <%= article.theme.title %>
      </div>
      <div class="article-card-details-rounded">
         <%= image_tag('ellipse.svg', class: 'ellipse-th') %>
      </div>
      <div class="article-card-details-time art-created">
          <% if TimeDifference.between(article.updated_at, Time.now).in_days.round >0 %>
            Il y a <%= TimeDifference.between(article.updated_at, Time.now).in_days.round %> jours
          <% else %>
            aujourd'hui
          <% end %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/shared/_articles_med_list.html.erb
<div class="favorites-title">
  <div class="favorites-title-col">
    <%= image_tag('article-new.svg') %>
    <span>Posts <%= scope %></span>
  </div>
</div>
<div class="article-cards">
  <% articles.each do |article| %>
  <div class="article-card">
    <a href=<%= article_path(article) %>>
      <div class="article-card-image"  style="background: url(
            <% if (article.picture.attached?) %>
                <%= cl_image_path(article.picture.key) %>
              <% else %>
                <%= image_path('frontlorem.jpg') %>
              <% end %>
                ), #F4EAF8; background-repeat: no-repeat; background-size: cover; background-position: 50% 50%; ">
      </div>
      <div class="article-card-title art-title">
        <%= article.title %>
      </div>
    </a>
    <div class="article-card-details">
      <% if avatar_visible == true %>
      <div class="article-card-details-avatar">
        <div class="">
          <%= link_to profiles_path(article.user.id) do %>
            <% if (article.user.picture.attached?) %>
            <%= cl_image_tag(article.user.picture.key, class: 'avatar-small') %>
              <% else %>
            <%= image_tag('avatar.png', class: 'avatar-small') %>
            <% end %>
          <% end %>
        </div>
        <div class="article-card-details-name">
          <span class="mini-user-name"><%= article.user.username %></span>
        </div>
      </div>
      <% end %>
      <a href=<%= theme_path(article.theme) %>>
      <div class="article-card-details-theme art-theme">
        <%= article.theme.title %>
      </div>
      </a>
      <div class="article-card-details-rounded">
         <%= image_tag('ellipse.svg', class: 'ellipse-th') %>
      </div>
      <div class="article-card-details-time art-created">
          <% if TimeDifference.between(article.created_at, Time.now).in_days.round >0 %>
            Il y a <%= TimeDifference.between(article.created_at, Time.now).in_days.round %> jours
          <% else %>
            aujourd'hui
          <% end %>
      </div>
    </div>
    <a href=<%= article_path(article) %>>
    <div class="article-card-details-content">
       <%= article.content %>
    </div>
    </a>
  </div>
  <% end %>
</div>

app/views/shared/_articles_med_list_col.html.erb
<div class="favorites-title">
  <div class="favorites-title-col">
    <%= image_tag('article-new.svg') %>
    <span>Posts <%= scope %></span>
  </div>
</div>
<div class="article-cards-col">
  <% articles.each do |article| %>
  <div class="article-card">
    <a href=<%= article_path(article) %>>
      <div class="article-card-image"  style="background: url(
            <% if (article.picture.attached?) %>
                <%= cl_image_path(article.picture.key) %>
              <% else %>
                <%= image_path('frontlorem.jpg') %>
              <% end %>
                ), #F4EAF8; background-repeat: no-repeat; background-size: cover; background-position: 50% 50%; width: 100%;">
      </div>
      <div class="article-card-title art-title">
        <%= article.title %>
      </div>
    </a>
    <div class="article-card-details">
      <% if avatar_visible == true %>
      <div class="article-card-details-avatar">
        <div class="">
          <%= link_to profiles_path(article.user.id) do %>
            <% if (article.user.picture.attached?) %>
            <%= cl_image_tag(article.user.picture.key, class: 'avatar-small') %>
              <% else %>
            <%= image_tag('avatar.png', class: 'avatar-small') %>
            <% end %>
          <% end %>
        </div>
        <div class="article-card-details-name">
          <span class="mini-user-name"><%= article.user.username %></span>
        </div>
      </div>
      <% end %>
      <a href=<%= theme_path(article.theme) %>>
      <div class="article-card-details-theme art-theme">
        <%= article.theme.title %>
      </div>
      </a>
      <div class="article-card-details-rounded">
         <%= image_tag('ellipse.svg', class: 'ellipse-th') %>
      </div>
      <div class="article-card-details-time art-created">
          <% if TimeDifference.between(article.created_at, Time.now).in_days.round >0 %>
            Il y a <%= TimeDifference.between(article.created_at, Time.now).in_days.round %> jours
          <% else %>
            aujourd'hui
          <% end %>
      </div>
    </div>
    <a href=<%= article_path(article) %>>
    <div class="article-card-details-content">
       <%= article.content %>
    </div>
    </a>
  </div>
  <% end %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" >
  <div class="container text-center">
    <h1><strong> <span class="strong-title">AITIO Draft</span> </strong></h1>
    <p></p>
    <% if user_signed_in? %>
    <%= link_to "Accueil", home_path, class: "btn purple white"%>
    <% else %>
    <%= link_to "Connexion", 'users/sign_in', class: "btn purple white"%>
    <% end %>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form_searchbar.erb
    <div class="search-bar">
      <%= form_tag currentpath, class: 'mybar', method: :get do %>
        <%= text_field_tag :query,
          params[:query],
          class: "form-control",
          placeholder: placeholder_value
        %>
      <div class="submit-box">
        <%= image_submit_tag 'magnifier.svg', class: "" %>
      </div>
      <% end %>
    </div>

app/views/shared/_macro_theme_list.erb
  <div class="favorites-title themes-title-all">
    <div class="favorites-title-col">
      <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="#902CB8" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-compass"><circle cx="12" cy="12" r="10"></circle><polygon points="16.24 7.76 14.12 14.12 7.76 16.24 9.88 9.88 16.24 7.76"></polygon></svg>
      <span>Tous les thèmes<%= scope %></span>
    </div>
    <% if add_arrow %>
      <%= link_to  image_tag('arrow-double-fat.svg'), arrowthemepath %>
    <% end %>
  </div>
 <div class="macro-themes-list">
  <% @themes.each do |theme| %>
    <a href="<%= theme_path(theme) %>">
      <div class="macro-theme-card" style="background: url(
        <% if (theme.picture.attached?) %>
            <%= cl_image_path(theme.picture.key) %>
          <% else %>
            <%= image_path('frontlorem.jpg') %>
          <% end %>
            ); background-repeat: no-repeat; background-size: 100% 50%; background-position: 50% 0%;">
        <span class="font-title"><%= theme.title %></span>
        <div class="icons">
          <div class="bookmark-icon">
            <%= link_to create_fav_th_path(theme.id), method: :post do %>
              <svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><path d="M19 21L12 16L5 21V5C5 4.46957 5.21071 3.96086 5.58579 3.58579C5.96086 3.21071 6.46957 3 7 3H17C17.5304 3 18.0391 3.21071 18.4142 3.58579C18.7893 3.96086 19 4.46957 19 5V21Z" stroke="#8A8B8F" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"/></svg>
            <% end %>
          </div>

          <div class="counter-macro counter-icon">
            <%= image_tag('eye.svg') %>
            <%= Favorite.where(favoritable_id: theme.id).count %>
          </div>
        </div>
      </div>
    </a>
  <% end %>
</div>

app/views/shared/_micro_theme_list.html copy.erb
  <div class="favorites-title">
    <div class="favorites-title-col">
      <%= image_tag('bookmark-alone-purple.svg') %>
      <span>Thèmes <%= scope %></span>
    </div>
    <% if add_arrow %>
      <%= link_to  image_tag('arrow-double-fat.svg'), arrowthemepath %>
    <% end %>
  </div>
 <div class="micro-themes-list">
  <% themes.each do |theme| %>
    <a href="<%= theme_path(theme) %>">
      <div class="micro-theme-card" style="background: url(
        <% if (theme.picture.attached?) %>
            <%= cl_image_path(theme.picture.key) %>
          <% else %>
            <%= image_path('frontlorem.jpg') %>
          <% end %>
            ); background-repeat: no-repeat; background-size: 100% 45%; background-position: 50% 0%;">
        <span><%= theme.title %></span>
        <div class="counter">
          <%= image_tag('eye.svg') %>
          <%= Favorite.where(favoritable_id: theme.id).count %>
        </div>
      </div>
    </a>
  <% end %>
</div>

app/views/shared/_modal_article_new.html.erb
<div class="modal fade" id="modal_article" tabindex="-1" aria-labelledby="modal_articleLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal_articleLabel">Ce que je veux partager</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="my-modal-body">
        <%= simple_form_for article, url: articles_path, method: :post do |f| %>
          <%= f.input :title, label: "Titre" %>
          <%= f.association :theme, label: "Thème", input_html: { id: 'mySelect'} %>
          <%= f.input :content, label: "Message", placeholder: "ce que vous voulez partager..." %>
           <div class="button-div">
              <label for="file-input">
              <%= f.input :picture, input_html: { style: 'display: none;' }, as: :file %>
              </label>
              <%= f.submit  "OK",  class: "modal-submit" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_modal_article_th_new.html.erb
<%= csrf_meta_tags %>
<div class="modal fade" id="modal_article" tabindex="-1" aria-labelledby="modal_articleLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="modal_articleLabel">Ce que je veux partager</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="my-modal-body">
        <%= simple_form_for article, url: create_art_selectedth_path, method: :post do |f| %>
          <%= f.input :title, label: "Titre" %>
          <%= f.association :theme, label: "Thème", label: false, selected: themes_list.id, input_html: { style: 'display: none;' } %>
          <%= f.input :content, label: "Message", placeholder: "ce que vous voulez partager..." %>
           <div class="button-div">
              <label for="file-input">
              <%= f.input :picture, input_html: { style: 'display: none;' }, as: :file %>
              </label>
              <%= f.submit  "OK",  class: "modal-submit" %>
            </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="my-navbar">
  <div class="navbar-cover">
  </div>
    <%= link_to home_path do %>
      <%= image_tag "btn-home-home.svg", class: "home-logo #{@home_active}" %>
    <% end %>
    <%= link_to wall_path do %>
      <%= image_tag "btn-home-discover.svg", class: "discover-logo  #{@discover_active}" %>
    <% end %>
      <%= image_tag "btn-home-create.svg", class: "create-logo", data: { toggle: "modal", target: "#modal_article" } %>
    <%= link_to bookmarks_path do %>
      <%= image_tag "btn-home-favorite.svg", class: "favorite-logo  #{@favorite_active}" %>
    <% end %>
    <%= image_tag "btn-home-user.svg", class: "me-logo #{@me_active}" %>
  <div class="mon_menu">
    <ul>
     <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Profil', dashboard_path, class:"padding-before" %>
            </li>
            <li class="nav-item">
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item log-out-item" %>
            </li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Login", new_user_session_path, class: "nav-link" %>
            </li>
     <% end %>
    </ul>
  </div>
</div>

app/views/shared/_user_profile.erb
 <div class="card-profile">
  <div class="profile-background">
    <% if user.picture.attached? %>
    <%=  cl_image_tag user.picture.key, class: "mon-avatar", alt: "avatar-large" %>
    <%  else %>
    <%= image_tag('avatar.png', class: "mon-avatar")%>
    <% end %>
  </div>
  <div class="profile-description">
    <h3><%= user.username %></h3>
    <span><%= user.state.text %></span>
  </div>
  <div class="follow-details">
    <div class="following follow-box">
      <span><%= follow_users_nb %></span><span class="follow-box-title">suivis</span>
    </div>
    <% case star %>
    <% when  "active" %>
      <div class="likes  follow-box">
        <%= link_to  image_tag('star-full.svg', class: "markup-star"), profiles_path(user), method: :patch %>
      </div>
    <% when "inactive" %>
      <div class="likes  follow-box">
        <%= link_to image_tag('star-empty.svg', class: "markup-star"), profiles_path(user), method: :patch %>
      </div>
    <% end %>
    <div class="followers  follow-box">
      <span><%= follower_users_nb %></span><span class="follow-box-title">suivi par</span>
    </div>
    <% if user == current_user %>
    <div class="likes  follow-box">
      <span><%= likes %></span><span class="follow-box-title">réactions</span>
    </div>
    <% end %>
  </div>
  <% if user == current_user %>
  <div class="edit-zone">
    <%= link_to "edit profile", edit_user_registration_path, class: 'btn-details' %>
    <%= link_to image_tag('bookmark-alone.svg', class: 'favorite-icon'), favorites_th_path, class: 'btn-favorite' %>
  </div>
  <% end %>
  <div class="biography">
    <p>
      <% if user.biography %>
        <%= user.biography %>
      <% else %>
        Je suis une personne qui partagera quelques mots plus tard sur qui je suis...
      <% end %>

    </p>
  </div>
</div>

app/views/shared/_user_profile.html.erb
 <div class="card-profile">
  <div class="profile-background">
    <% if user.picture.attached? %>
    <%=  cl_image_tag user.picture.key, class: "mon-avatar", alt: "avatar-large" %>
    <%  else %>
    <%= image_tag('avatar.png', class: "mon-avatar")%>
    <% end %>
  </div>
  <div class="profile-description">
    <h3><%= user.username %></h3>
    <span><%= user.state.text %></span>
  </div>
  <div class="follow-details">
    <div class="following follow-box">
      <span><%= follow_users_nb %></span><span class="follow-box-title">suivis</span>
    </div>
    <% case star %>
    <% when  "active" %>
      <div class="likes  follow-box">
        <%= link_to  image_tag('star-full.svg', class: "markup-star"), profiles_path(user), method: :patch %>
      </div>
    <% when "inactive" %>
      <div class="likes  follow-box">
        <%= link_to image_tag('star-empty.svg', class: "markup-star"), profiles_path(user), method: :patch %>
      </div>
    <% end %>
    <div class="followers  follow-box">
      <span><%= follower_users_nb %></span><span class="follow-box-title">suivi par</span>
    </div>
    <% if user == current_user %>
    <div class="likes  follow-box">
      <span><%= likes %></span><span class="follow-box-title">réactions</span>
    </div>
    <% end %>
  </div>
  <% if user == current_user %>
  <div class="edit-zone">
    <%= link_to "edit profile", edit_user_registration_path, class: 'btn-details' %>
  </div>
  <% end %>
  <div class="biography">
    <p>
      <% if user.biography %>
        <%= user.biography %>
      <% else %>
        Je suis une personne qui partagera quelques mots plus tard sur qui je suis...
      <% end %>
    </p>
  </div>
</div>